### PR TITLE
Make strategic function application operators handle strategies correctly

### LINKED ISSUE #43: Strategic function application operators don't quite match their documentation
These operators all perform evaluation to WHNF, whether or not the strategies do so. I don't have a strong opinion about whether the behavior or the documentation should change, but the current situation is strange. Example:

```haskell
-- | Sequential function application. The argument is evaluated using
--   the given strategy before it is given to the function.
($|) :: (a -> b) -> Strategy a -> a -> b
f $| s  = \ x -> let z = x `using` s in z `pseq` f z
```

Based on the documentation, I'd have expected something more like

```haskell
f $| s = \ x -> runEval (f <$> s x)
```

### PR DESCRIPTION
**Pull request by konsumlamm**
Fixes #43.

### CODE REVIEW

**Comment by konsumlamm** [comment]
@simonmar what do you think?

**Comment by konsumlamm** [comment]
@simonmar ?

**Review by treeowl — APPROVED** [review]
LGTM!

**Comment by konsumlamm** [comment]
@Kleidukos do you still want to review or can I go ahead and merge?

**Review by Kleidukos — APPROVED** [review]
LGTM

**Pull request merged**
