### PR TITLE
Allow base-4.14, add ghc-8.10 job

### PR DESCRIPTION
**Pull request by phadej**
I made a corresponding revision https://hackage.haskell.org/package/parallel-3.2.2.0/revisions/, so no action is required after the merge.

### CODE REVIEW

**Comment by phadej** [comment]
ping. @RyanGlScott can you merge this?

**Comment by RyanGlScott** [comment]
I'm no longer on the CLC, but for some reason I still have push access to this repo, so I suppose I could land this. On the other hand, this is probably something I shouldn't make a habit of...

**Comment by phadej** [comment]
Ryan, ok I guess I have to ping @haskell/core-language-committee (do you see whether that group is up to date?)

**Comment by cartazio** [comment]
Core library committee?

Looks good to me, just bumping constraints and improving ci.

Cc @chessai @hvr @emilypi @hvr

**Comment by chessai** [comment]
@phadej i think you pinged core-language-committee. You probably want @haskell/core-libraries-committee

**Comment by phadej** [comment]
Oh, I wasn't aware there *is* a core-language-committee in addtion to core-libraries-committee. Both are CLC!

**Pull request merged**
