### PR TITLE
bump base upper bound to < 4.18

### PR DESCRIPTION
**Pull request by mitchellwrosen**

### CODE REVIEW

**Comment by phadej** [comment]
I made a corresponding revision https://hackage.haskell.org/package/parallel-3.2.2.0/revisions/

**Comment by mitchellwrosen** [comment]
Copying a comment I just made from `haskell/attoparsec`:

> Ok, thanks. ... unfortunately now the source repository is now out of sync with what's on Hackage sweat_smile
>
> I'll leave this open and the maintainer, whoever they are, can choose to merge, or not, and separately decide if they want to also > add an x-revision field to the cabal file to match what's on Hackage.

**Comment by Bodigrim** [comment]
@mitchellwrosen cabal files have been out of sync for three years, this is the fifth revision. I would not worry about that.

**Comment by mitchellwrosen** [comment]
Hehe, fair enough!

**Comment by TristanCacqueray** [comment]
Hi, could you please do another revision for base-4.18 please.

**Comment by Bodigrim** [comment]
@TristanCacqueray please raise a pull request first and give maintainers time to react.

**Comment by TristanCacqueray** [comment]
@Bodigrim sure, it's #64. thank you!

**Pull request closed without merging**
